spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  database-schema-update: true
  idm.app.admin.user-id: admin
  idm.app.admin.password: test
  idm.app.admin.email: admin@example.com
  idm.app.admin.first-name: Admin
  idm.app.admin.last-name: User
  idm.engine.configurator.database-schema-update: true
  idm:
    app:
      enabled: true
  modeler:
    app:
      enabled: true
  task:
    app:
      enabled: true
  common:
    app:
      idm-url: http://localhost:8080/flowable-idm
      idm-admin:
        user: admin
        password: test
  xml:
    encoding: UTF-8
  rest:
    app:
      authentication-mode: any-user
      # authentication-mode: verify-privilege
      enabled: true
      root: flowable-rest
      swagger-enabled: true
  ui:
    default-locale: en
logging:
  file:
    name: ./logs/flowable.log
  level:
    org.springframework: DEBUG
    org.flowable: DEBUG
    com.zaxxer.hikari: DEBUG

server:
  port: 8084
  servlet:
    context-path: /
