spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flowable?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

flowable:
  database-schema-update: true
  idm.app.admin.user-id: admin
  idm.app.admin.password: test
  idm.app.admin.email: admin@example.com
  idm.app.admin.first-name: Admin
  idm.app.admin.last-name: Dragon
  idm.engine.configurator.database-schema-update: true
  idm:
    app:
      enabled: true
  modeler:
    app:
      enabled: true
  common:
    app:
      idm-url: http://localhost:8080/flowable-idm
      idm-admin:
        user: admin
        password: test
  rest:
    app:
      authentication-mode: any-user
      enabled: true
      root: flowable-rest
      swagger-enabled: true
logging:
  file:
    name: /logs/flowable.log
  level:
    org.springframework: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.web: DEBUG
    org.flowable: DEBUG

server:
  port: 9898
  servlet:
    context-path: /
